# Project data
projects = [
    {
        'id': 1,
        'title': 'Augmented Mirror',
        'description': '',
        'image': 'old_project_1.gif',
        'long_description': 'Dance  Poke It  Bounce  ',
        'technologies': ['Augmented Reality', 'Computer Vision'],
        'github_link': '',
        'live_demo': '',
    },
    {
        'id': 2,
        'title': 'Augmented Reality Communication',
        'description': '',
        'image': 'old_project_2.gif',
        'long_description': '',
        'technologies': ['Augmented Reality'],
        'github_link': '',
        'live_demo': '',
    },
    {
        'id': 3,
        'title': 'Cairn Candle',
        'description': '',
        'image': 'old_project_3.gif',
        'long_description': '',
        'technologies': ['Python', 'C++', 'Computer Vision'],
        'github_link': '',
        'live_demo': '',
    },
    {
        'id': 4,
        'title': 'Dynamic Training in AR for Musical Practice',
        'description': 'Basics of the theremine module with tutorial implemented on Art Table',
        'image': 'old_project_4.gif',
        'long_description': 'Basics of the theremine module with tutorial implemented on Art Table  Theremine module on the Augmented Mirror  ',
        'technologies': ['Augmented Reality', 'Audio Processing'],
        'github_link': '',
        'live_demo': '',
    },
    {
        'id': 5,
        'title': 'Image Processing Software',
        'description': '',
        'image': 'old_project_5.gif',
        'long_description': '',
        'technologies': ['Software Development'],
        'github_link': '',
        'live_demo': '',
    },
    {
        'id': 6,
        'title': 'Industrial Sorting Circuit and Robotic',
        'description': '',
        'image': 'old_project_6.gif',
        'long_description': '',
        'technologies': ['Robotics'],
        'github_link': '',
        'live_demo': '',
    },
    {
        'id': 7,
        'title': 'Interactive Avatar with Pose Estimation',
        'description': '',
        'image': 'old_project_7.gif',
        'long_description': '',
        'technologies': ['Motion Tracking'],
        'github_link': '',
        'live_demo': '',
    },
    {
        'id': 8,
        'title': 'Interactive Musical Score',
        'description': '',
        'image': 'old_project_8.gif',
        'long_description': '',
        'technologies': ['Audio Processing'],
        'github_link': '',
        'live_demo': '',
    },
    {
        'id': 9,
        'title': 'Master Thesis',
        'description': '',
        'image': 'old_project_9.gif',
        'long_description': '',
        'technologies': ['Python', 'C++', 'Computer Vision'],
        'github_link': '',
        'live_demo': '',
    },
    {
        'id': 10,
        'title': 'Miniature suspended tramway',
        'description': '',
        'image': 'old_project_10.gif',
        'long_description': '',
        'technologies': ['Python', 'C++', 'Computer Vision'],
        'github_link': '',
        'live_demo': '',
    },
    {
        'id': 11,
        'title': 'Sign Language Recognition Module',
        'description': '',
        'image': 'old_project_11.gif',
        'long_description': '',
        'technologies': ['Machine Learning'],
        'github_link': '',
        'live_demo': '',
    },
    {
        'id': 12,
        'title': 'Sign Language Video Game in Augmented Reality',
        'description': '',
        'image': 'old_project_12.gif',
        'long_description': '',
        'technologies': ['Augmented Reality'],
        'github_link': '',
        'live_demo': '',
    },
]
